// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS9NFGCyPEK97f5HZQlpX_omOBGVWbRLo',
    appId: '1:442040484554:web:305bc800cc93708308ea33',
    messagingSenderId: '442040484554',
    projectId: 'votaciones-36962',
    authDomain: 'votaciones-36962.firebaseapp.com',
    storageBucket: 'votaciones-36962.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUF3-Pgw3g-LqWZ8sWF9wIqGKhmtl2hJ4',
    appId: '1:442040484554:android:e6c0374323dc9ae408ea33',
    messagingSenderId: '442040484554',
    projectId: 'votaciones-36962',
    storageBucket: 'votaciones-36962.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlytxPtWixVuwomJwoHONSUk93TVOgQIo',
    appId: '1:442040484554:ios:d28f730e01af1ace08ea33',
    messagingSenderId: '442040484554',
    projectId: 'votaciones-36962',
    storageBucket: 'votaciones-36962.appspot.com',
    iosBundleId: 'com.example.votaciones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlytxPtWixVuwomJwoHONSUk93TVOgQIo',
    appId: '1:442040484554:ios:d28f730e01af1ace08ea33',
    messagingSenderId: '442040484554',
    projectId: 'votaciones-36962',
    storageBucket: 'votaciones-36962.appspot.com',
    iosBundleId: 'com.example.votaciones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS9NFGCyPEK97f5HZQlpX_omOBGVWbRLo',
    appId: '1:442040484554:web:bb94322f6eebf53a08ea33',
    messagingSenderId: '442040484554',
    projectId: 'votaciones-36962',
    authDomain: 'votaciones-36962.firebaseapp.com',
    storageBucket: 'votaciones-36962.appspot.com',
  );
}
